export interface ChallengeData {
  id: number;
  title: string;
  description: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  category: string;
  hint: string;
  flag: string;
  points: number;
  order: number;
}

export const challenges: ChallengeData[] = [
  {
    id: 1,
    title: 'Exposed Environment Configuration',
    description: 'The application accidentally exposes its environment configuration file through the web server. Find the exposed .env file and retrieve the flag.',
    difficulty: 'Easy',
    category: 'Configuration Exposure',
    hint: 'Try requesting a file that web servers should never serve: /.env',
    flag: 'FLAG{CARTHAGE_ENV_EXPOSED}',
    points: 50,
    order: 1,
  },
  {
    id: 2,
    title: 'Frontend Secret Discovery',
    description: 'Sensitive configuration data is embedded in the client-side JavaScript bundle. Inspect the application source to find exposed secrets.',
    difficulty: 'Easy',
    category: 'Client-Side Exposure',
    hint: 'Use browser DevTools → Sources tab or View Page Source to inspect the JavaScript bundle.',
    flag: 'FLAG{FRONTEND_CONFIG_FOUND}',
    points: 50,
    order: 2,
  },
  {
    id: 3,
    title: 'Public User Database',
    description: 'An API endpoint returns user records without requiring any authentication. Discover the endpoint and document the exposed data.',
    difficulty: 'Easy',
    category: 'API Security',
    hint: 'Monitor network requests in DevTools while browsing the site, or try common API paths like /api/users.',
    flag: 'FLAG{PUBLIC_USERS_API}',
    points: 75,
    order: 3,
  },
  {
    id: 4,
    title: 'Broken Object-Level Authorization (IDOR)',
    description: 'By manipulating ID parameters in API requests, you can access other users\' records. Demonstrate accessing another user\'s library card.',
    difficulty: 'Medium',
    category: 'Access Control',
    hint: 'After finding the users API, try changing the ID number in /api/users/[id] or /api/library-cards/[id].',
    flag: 'FLAG{BROKEN_OBJECT_AUTH}',
    points: 100,
    order: 4,
  },
  {
    id: 5,
    title: 'Reflected Cross-Site Scripting (XSS)',
    description: 'The book search functionality reflects user input without proper sanitization. Find and document the reflected XSS vulnerability.',
    difficulty: 'Medium',
    category: 'XSS',
    hint: 'Try entering HTML/script tags in the book search form at /books.',
    flag: 'FLAG{REFLECTED_XSS}',
    points: 100,
    order: 5,
  },
  {
    id: 6,
    title: 'Stored Cross-Site Scripting (XSS)',
    description: 'The contact form stores user input that is later rendered without sanitization. Submit and trigger a stored XSS payload.',
    difficulty: 'Medium',
    category: 'XSS',
    hint: 'Submit a message with a script tag via /contact or the API, then check where messages are displayed.',
    flag: 'FLAG{STORED_XSS}',
    points: 125,
    order: 6,
  },
  {
    id: 7,
    title: 'DOM-Based Cross-Site Scripting',
    description: 'A client-side search component uses an unsafe JavaScript sink. Analyze the JavaScript source code to identify the DOM XSS vulnerability.',
    difficulty: 'Hard',
    category: 'XSS',
    hint: 'Look for innerHTML assignments in the JavaScript bundle using DevTools → Sources tab.',
    flag: 'FLAG{DOM_XSS_SINK}',
    points: 150,
    order: 7,
  },
  {
    id: 8,
    title: 'Weak Authentication',
    description: 'The application has demo accounts with weak passwords. Identify the weak credential pair and gain unauthorized access.',
    difficulty: 'Easy',
    category: 'Authentication',
    hint: 'Try common test accounts like demo@example.test with obvious passwords.',
    flag: 'FLAG{WEAK_AUTH_DEMO}',
    points: 75,
    order: 8,
  },
  {
    id: 9,
    title: 'JWT Misconfiguration',
    description: 'The authentication system uses JWT tokens with a weak signing secret. Inspect your authentication token to identify the weakness.',
    difficulty: 'Medium',
    category: 'Authentication',
    hint: 'After logging in, inspect the JWT token in DevTools → Application → Cookies or Local Storage.',
    flag: 'FLAG{JWT_WEAK_SECRET}',
    points: 100,
    order: 9,
  },
  {
    id: 10,
    title: 'Debug Information Disclosure',
    description: 'A debug endpoint exposes internal application configuration. Find and access the debug endpoint.',
    difficulty: 'Easy',
    category: 'Information Disclosure',
    hint: 'Try accessing /debug directly in your browser.',
    flag: 'FLAG{DEBUG_ENDPOINT_FOUND}',
    points: 50,
    order: 10,
  },
  {
    id: 11,
    title: 'Missing Security Headers',
    description: 'The application is missing critical security headers. Verify which security headers are absent from HTTP responses.',
    difficulty: 'Medium',
    category: 'Security Misconfiguration',
    hint: 'Use curl -I or browser DevTools → Network tab to inspect response headers.',
    flag: 'FLAG{HEADERS_MISSING}',
    points: 75,
    order: 11,
  },
  {
    id: 12,
    title: 'CORS Misconfiguration',
    description: 'The API has overly permissive CORS settings that could allow cross-origin attacks. Identify the vulnerable CORS configuration.',
    difficulty: 'Medium',
    category: 'Security Misconfiguration',
    hint: 'Check for Access-Control-Allow-Origin: * headers in API responses.',
    flag: 'FLAG{CORS_WIDE_OPEN}',
    points: 100,
    order: 12,
  },
  {
    id: 13,
    title: 'Excessive API Data Exposure',
    description: 'API endpoints return more data than the frontend requires, leaking sensitive information. Identify the over-disclosure.',
    difficulty: 'Medium',
    category: 'Information Disclosure',
    hint: 'Compare what data the frontend displays vs what the API actually returns.',
    flag: 'FLAG{EXCESSIVE_DATA_EXPOSURE}',
    points: 75,
    order: 13,
  },
  {
    id: 14,
    title: 'Admin Access Control Bypass',
    description: 'Administrative API endpoints lack proper authorization checks. Attempt to access admin functionality without proper credentials.',
    difficulty: 'Hard',
    category: 'Access Control',
    hint: 'Try accessing /api/admin/users without providing any authentication token.',
    flag: 'FLAG{ADMIN_AUTHZ_BYPASS}',
    points: 150,
    order: 14,
  },
  {
    id: 15,
    title: 'Final Security Assessment',
    description: 'Combine all your findings to complete a comprehensive security assessment of the Carthage Library application. Submit the final flag.',
    difficulty: 'Hard',
    category: 'Assessment',
    hint: 'Complete all previous challenges and compile your evidence into a final report.',
    flag: 'FLAG{CARTHAGE_ASSESSMENT_COMPLETE}',
    points: 200,
    order: 15,
  },
];
